# Generated by Django 2.0.3 on 2018-04-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(max_length=16),
        ),
    ]
