# Generated by Django 2.0.4 on 2018-04-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_auto_20180404_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=1)),
            ],
        ),
    ]
