# Generated by Django 2.0.4 on 2018-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
